apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claimX
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 11Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hserverX-deployment
spec:
  selector:
    matchLabels:
      app: hserverX
  replicas: 1
  template:
    metadata:
      labels:
        app: hserverX
    spec:
      containers:
        
      - name: hserverX
        image: gcr.io/PROJECT_ID/hserver
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.2"
        ports:
        - containerPort: 3500
        volumeMounts:
          - name: volumeX
            mountPath: /storage
        env:
        - name: FORCE_REDEPLOY
          value: 'DEPLOY_TIME'
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3500
            
      volumes:

        - name: volumeX
          persistentVolumeClaim:
            claimName: claimX

