apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: certX
spec:
  domains:
    - domainX
---
apiVersion: v1
kind: Service
metadata:
  name: hserviceX
spec:
  ports:
    - port: 3500
      protocol: TCP
      targetPort: 3500
  selector:
    app: cserverX
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hingressX
  annotations:
    kubernetes.io/ingress.global-static-ip-name: ipX
    networking.gke.io/managed-certificates: certX
spec:
  backend:
    serviceName: hserviceX
    servicePort: 3500
